// Unique download page — this is the link buyers click from their email.
// It verifies the signed token (proving it was genuinely generated by
// our webhook after a real payment) then redirects to the actual file.

import crypto from "crypto";

const DRIVE_LINKS = {
  "zero-to-trader": "https://drive.google.com/file/d/1WUH-JyctTKCeYb7d5OA5NIgyymOKeBHJ/view?usp=sharing",
  "screener-guide": "https://drive.google.com/file/d/1bCGHwBVjoOmcaCyIO5xd6bthgoT_7KH6/view?usp=sharing",
};

function driveDirectDownloadUrl(shareUrl) {
  const match = shareUrl.match(/\/d\/([^/]+)/);
  const fileId = match ? match[1] : null;
  if (!fileId) return shareUrl; // fallback, shouldn't happen
  return `https://drive.google.com/uc?export=download&id=${fileId}`;
}

export default function handler(req, res) {
  const { token } = req.query;

  if (!token) {
    return res.status(400).send("Missing download token.");
  }

  let decoded;
  try {
    decoded = Buffer.from(token, "base64url").toString();
  } catch {
    return res.status(400).send("Invalid download link.");
  }

  const parts = decoded.split(":");
  const signature = parts.pop();
  const productId = parts.pop();
  const orderId = parts.join(":");

  const expectedSignature = crypto
    .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
    .update(`${orderId}:${productId}`)
    .digest("hex");

  if (signature !== expectedSignature || !DRIVE_LINKS[productId]) {
    return res.status(403).send("This download link is invalid or has expired.");
  }

  const directLink = driveDirectDownloadUrl(DRIVE_LINKS[productId]);
  res.writeHead(302, { Location: directLink });
  res.end();
}
